### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [white-gecko/musicxml2fmf#2]
i put the install command into the python terminal and got this
![Untitled](https://user-images.githubusercontent.com/36720741/206607943-105e8905-57d4-4566-a4b2-fd0b4ede122a.png)

**Comment by white-gecko** [comment]
You have to enter this command on the terminal, not within the Python interpreter.

**Comment by C4PTRAMPAGE** [comment]
well i don't know what i need to do then because putting this in cmd didn't work either even when i set the directory to the python install folder
